# -*- coding: utf-8 -*-
"""pythonproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YAi0RbQHiuL4MYjrEA8IbZuiaUDPkbuV
"""

import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
import os

FILE_NAME = 'expenses.csv'

def log_expense(amount, category, description=""):
    date = datetime.now().strftime('%Y-%m-%d')
    expense = pd.DataFrame([[date, amount, category, description]],
                           columns=['Date', 'Amount', 'Category', 'Description'])

    try:
        if os.path.exists(FILE_NAME):
            expense.to_csv(FILE_NAME, mode='a', header=False, index=False)
        else:
            expense.to_csv(FILE_NAME, index=False)
        print(f"Logged: ${amount:.2f} on {date} under '{category}'")
    except Exception as e:
        print(f"Error while logging expense: {e}")
def visualize_expenses():
    if not os.path.exists(FILE_NAME):
        print("No expenses logged yet!")
        return

    try:
        df = pd.read_csv(FILE_NAME)
        df['Date'] = pd.to_datetime(df['Date'])
        print("Loaded expenses:")
        print(df)
        category_totals = df.groupby('Category')['Amount'].sum().sort_values(ascending=False)
        print("\nSpending by Category:")
        print(category_totals)

        category_totals.plot(kind='bar', title='Spending by Category', colormap='Set3')
        plt.ylabel('Amount ($)')
        plt.tight_layout()
        plt.show()
        daily_totals = df.groupby('Date')['Amount'].sum()
        print("\nSpending Over Time:")
        print(daily_totals)

        daily_totals.plot(kind='line', marker='o', title='Spending Over Time', grid=True)
        plt.ylabel('Amount ($)')
        plt.xlabel('Date')
        plt.tight_layout()
        plt.show()

    except Exception as e:
        print(f"Error while visualizing expenses: {e}")
print("Logging example expenses...")
log_expense(12.5, "Food", "Lunch")
log_expense(35.0, "Transport", "Gas refill")
log_expense(50.0,"shopping", "clothes")

print("\nVisualizing expenses...")
visualize_expenses()